WIP Sessionと42 Oauth
RIFT-tokyo/transcendence-api pull request #16
Opened 2022-02-06 13:46 UTC by sasakiyudai

## チケットへのリンク
#13 #14 
## やったこと
POST /auth/login {"username": "syudai", "password": "password"}　→ 一週間有効なセッションIDをSet-Cookie

GET /auth/login & /auth/callback　→ 42oauthのログイン, 一週間有効なセッションIDをSet-Cookie(←これまだ実装できてない)

## やらないこと

## テスト
手動
## その他
WIP

2022-02-13 04:05 UTC, tkomatsu requested changes

2022-02-15 04:43 UTC, sasakiyudai commented on src/auth/auth.controller.ts
> +  @Redirect('http://localhost:4212', 307)
[34ca91b](https://github.com/RIFT-tokyo/transcendence-api/pull/16/commits/34ca91bbce8d9b389b672958cb0fa6c8e2d4223f)
done

2022-02-15 04:43 UTC, sasakiyudai commented on src/common/guards/ft-oauth-guard.ts
> +import { ExecutionContext, Injectable } from '@nestjs/common';
[2ff2c39](https://github.com/RIFT-tokyo/transcendence-api/pull/16/commits/2ff2c39fe7e126e3a45560c37d077ec9ca573577)
でdone

2022-02-15 04:43 UTC, sasakiyudai commented on src/migrations/1644132563068-add-password.ts
> +import {MigrationInterface, QueryRunner} from "typeorm";
[07f1066](https://github.com/RIFT-tokyo/transcendence-api/pull/16/commits/07f1066b7a9c6d04d513c5c1d022910b62880d5f)
でdone

2022-02-15 04:43 UTC, sasakiyudai commented on src/migrations/1644669762157-password-nullable-add-ft-id.ts
> +import {MigrationInterface, QueryRunner} from "typeorm";
[07f1066](https://github.com/RIFT-tokyo/transcendence-api/pull/16/commits/07f1066b7a9c6d04d513c5c1d022910b62880d5f)
でdone

2022-02-15 04:44 UTC, sasakiyudai commented on src/users/users.controller.ts
> +import { User } from '../entities/user.entity';
[40cd0f5](https://github.com/RIFT-tokyo/transcendence-api/pull/16/commits/40cd0f5cef8e3ac8efbcbee6bab946c7e3fdde8e)
でdone

2022-02-15 04:44 UTC, sasakiyudai commented on src/users/users.controller.ts
> +    const { password, ...others } = user;
[2d85c8e](https://github.com/RIFT-tokyo/transcendence-api/pull/16/commits/2d85c8e028b22f6b61b7ed5a7cc625068a579f9b)
でdone

2022-02-15 04:45 UTC, sasakiyudai commented on src/entities/user.entity.ts
> +  ft_id: number;
[8eda342](https://github.com/RIFT-tokyo/transcendence-api/pull/16/commits/8eda34262551e9fb7b45b7b8eccbc8f718150aaa)
でdone

2022-02-15 04:45 UTC, sasakiyudai commented on src/auth/auth.service.ts
> +      const { password, ...result } = user;
[2d85c8e](https://github.com/RIFT-tokyo/transcendence-api/pull/16/commits/2d85c8e028b22f6b61b7ed5a7cc625068a579f9b)
でdone

2022-02-15 04:46 UTC, sasakiyudai commented on src/main.ts
> +      cookie: { maxAge: 7 * 24 * 3600 * 1000 }, // 1 week
[8eda342](https://github.com/RIFT-tokyo/transcendence-api/pull/16/commits/8eda34262551e9fb7b45b7b8eccbc8f718150aaa)
でdone

2022-02-15 04:51 UTC, sasakiyudai commented on src/auth/ft-oauth.strategy.ts
> +      ft_id: profile.id,
[8eda342](https://github.com/RIFT-tokyo/transcendence-api/pull/16/commits/8eda34262551e9fb7b45b7b8eccbc8f718150aaa)
でdone

passwordを消していないのは、usersServcice.createUserでpasswordをハッシュ化する処理があってそこでは空のデータ(password)が許されないからです。
42 oauthで登録した人がusername, passwordのやり方でログインできるかに依るのでとりあえずこうしてる感じです。そこらへんの仕様が決まったら適当ではなくなると思います。

2022-02-15 10:08 UTC, tkomatsu requested changes
コメントした部分の確認お願いします！

2022-02-15 10:08 UTC, tkomatsu commented on src/users/users.dto.ts
> -  status_message: string;
消さないでくださいー

2022-02-15 12:28 UTC, sasakiyudai commented on src/auth/auth.controller.ts
> +  @Redirect(process.env.LOGIN_SUCCESS_URL, 307)
[d29bd9d](https://github.com/RIFT-tokyo/transcendence-api/pull/16/commits/d29bd9dd98959c624da68c3d6f59abe58acaae80)

2022-02-15 12:41 UTC, tkomatsu approved these changes
![LGTM](https://image.lgtmoon.dev/156502)

2022-02-15 12:41 UTC, merged