フォロー機能の追加
RIFT-tokyo/transcendence-api pull request #26
Opened 2022-02-19 07:25 UTC by tkomatsu

## チケットへのリンク
https://github.com/RIFT-tokyo/transcendence-api/issues/15
## やったこと
フォロー系のエンドポイントの処理を追加
## やらないこと

## テスト
1. マイグレーションを実行
2. `GET /users`, `GET /users/:id`, `GET /users/:id/following`, `GET /users/:id/followers`で、レスポンスに`following`, `followers`が含まれていることを確認
3. `PUT /users/following/:id`でフォローをして、`GET /users/:id`で`following`の数が増えているか確認、`GET /users/:id/following`でリストに追加されているか確認
4. `DELETE /users/following/:id`でアンフォローを実行、`GET /users/:id`, `GET /users/:id/following`で値が変更されているか確認
5. `GET /users/:id/following/:targetId`でフォローの有無を確認
## その他

2022-02-19 16:55 UTC, sasakiyudai requested changes

2022-02-19 16:55 UTC, sasakiyudai commented on src/users/users.controller.ts
> +      followers: user.followers?.length,
なんでこれみたく
`user.followers?.length`
?があるものもあれば、上のupdateUserとかには"?"がないんですか？

2022-02-19 16:55 UTC, sasakiyudai commented on src/users/users.service.ts
> +    }
この辺りのロジック(上のfollowとかunFollow関数とかも)getFollowing使いまわすといいかなって思うんですけどどうでしょう

2022-02-19 16:55 UTC, sasakiyudai commented on src/users/users.service.ts
> +    user.following.push(targetUser);
自分をフォローできますが、その回避はこのPRではやりませんか？

2022-02-19 23:41 UTC, tkomatsu commented on src/users/users.service.ts
> +    user.following.push(targetUser);
やらないとだめですね！

2022-02-19 23:50 UTC, tkomatsu commented on src/users/users.service.ts
> +    }
たしかに

2022-02-19 23:51 UTC, tkomatsu commented on src/users/users.service.ts
> +    }
ただ、follow/unfollowはUserが必要なので、そのままだと使えないので修正します

2022-02-20 00:43 UTC, tkomatsu commented on src/users/users.service.ts
> +    }
follow/unfollowに関してはUser自体がほしいこと、そのUserにはfollowersは含まずfollwoingだけを含めたいこと、followers/followingを含めるかどうかをオプションにした関数を作るとコードが分かりにくくなるとこ、からisFollowingのみgetFollowingを使うことにしました。

2022-02-20 00:52 UTC, tkomatsu commented on src/users/users.controller.ts
> +      followers: user.followers?.length,
`User.followers`, `User.following`は`User[]`ではありますが、その`User`には`followers`/`following`は含まれません。`?`をつけないとundefinedに対してlengthを呼び出すことになるため、`?`をつけています。
単に、`user`を返すようにすると、`User`のfollowers, followingが`User[]`であることと`ResponseUser`のfollowers, followingが`number`であることが干渉し、TypeScriptのエラーが出てしまうため、そのようにしています。

できれば、controller内で、`User`から`ResponseUser`に明示的に詰め替える処理を入れるといいんだろうなとは思います。
https://github.com/RIFT-tokyo/transcendence-api/issues/25
このチケットで解決するんじゃないかなと思います。

2022-02-20 03:59 UTC, sasakiyudai commented
![image](https://user-images.githubusercontent.com/66932739/154827901-6e71b458-0228-498e-ba57-9a97931e85f1.png)

2022-02-20 03:59 UTC, sasakiyudai approved these changes

2022-02-20 04:02 UTC, merged