User status websocket
RIFT-tokyo/transcendence-api pull request #52
Opened 2022-04-15 15:21 UTC by sasakiyudai

## チケットへのリンク
fix 
## やったこと

## やらないこと

## テスト

## その他
see https://github.com/RIFT-tokyo/transcendence-front/pull/61

2022-04-16 10:25 UTC, tkomatsu commented
パッケージ不足してるので動かないですー
```shell-session
[10:21:21 AM] Starting compilation in watch mode...
transcendence-env-api-1  |
transcendence-env-api-1  | src/app.gateway.ts:9:8 - error TS2307: Cannot find module '@nestjs/websockets' or its corresponding type declarations.
transcendence-env-api-1  |
transcendence-env-api-1  | 9 } from '@nestjs/websockets';
transcendence-env-api-1  |          ~~~~~~~~~~~~~~~~~~~~
transcendence-env-api-1  |
transcendence-env-api-1  | src/app.gateway.ts:10:32 - error TS2307: Cannot find module 'socket.io' or its corresponding type declarations.
transcendence-env-api-1  |
transcendence-env-api-1  | 10 import { Socket, Server } from 'socket.io';
transcendence-env-api-1  |                                   ~~~~~~~~~~~
transcendence-env-api-1  |
transcendence-env-api-1  | src/users/users.gateway.ts:8:8 - error TS2307: Cannot find module '@nestjs/websockets' or its corresponding type declarations.
transcendence-env-api-1  |
transcendence-env-api-1  | 8 } from '@nestjs/websockets';
transcendence-env-api-1  |          ~~~~~~~~~~~~~~~~~~~~
transcendence-env-api-1  |
transcendence-env-api-1  | src/users/users.gateway.ts:9:32 - error TS2307: Cannot find module 'socket.io' or its corresponding type declarations.
transcendence-env-api-1  |
transcendence-env-api-1  | 9 import { Socket, Server } from 'socket.io';
transcendence-env-api-1  |                                  ~~~~~~~~~~~
transcendence-env-api-1  |
transcendence-env-api-1  | [10:21:26 AM] Found 4 errors. Watching for file changes.
transcendence-env-api-1  |
```

2022-04-16 10:26 UTC, tkomatsu commented on src/app.module.ts
> -      logging: 'all',
SQLのログは確かに邪魔な時もあるのですが、基本的には実行されたクエリを確認して無駄な処理をしていないかを確認するもののため、消さないで欲しいです。
これから少しずつ複雑なクエリを叩くことになっていくはずで、その時は実行されたクエリを見るようにしたいので。
n+1問題とかもクエリみたらわかるようになると思います。

2022-04-17 12:03 UTC, sasakiyudai commented on src/app.module.ts
> -      logging: 'all',
戻しました[39331c5](https://github.com/RIFT-tokyo/transcendence-api/pull/52/commits/39331c5d75429d80f6bf001c3c8a5f46ef46712d)

2022-04-17 12:22 UTC, sasakiyudai commented
> パッケージ不足してるので動かないですー


直しました

2022-04-18 13:21 UTC, tkomatsu requested changes

2022-04-18 13:21 UTC, tkomatsu commented on src/app.gateway.ts
> +  handleConnection(@ConnectedSocket() client: Socket) {}
エディタでerrorとwarningが出てます。

2022-04-18 13:21 UTC, tkomatsu commented on src/users/users.gateway.ts
> +    console.log(`Client connected: ${userID}`);
ロギングをしたいのであれば、`console.log`は使用せずロガーを使って欲しいです。

2022-04-18 13:21 UTC, tkomatsu commented on src/users/users.gateway.ts
> +    @MessageBody() body: any,
anyは使わずpayloadの型定義を作成してください。
今のままだとドキュメントに沿わない形式でもよいことになります。

2022-04-20 12:12 UTC, sasakiyudai commented on src/users/users.gateway.ts
> +    @MessageBody() body: any,
[e44b3b1](https://github.com/RIFT-tokyo/transcendence-api/pull/52/commits/e44b3b10ca47a0a3192f8fab63ae0e0a62f31358)で対応

2022-04-20 12:12 UTC, sasakiyudai commented on src/users/users.gateway.ts
> +    console.log(`Client connected: ${userID}`);
[e44b3b1](https://github.com/RIFT-tokyo/transcendence-api/pull/52/commits/e44b3b10ca47a0a3192f8fab63ae0e0a62f31358)で対応

2022-04-20 12:12 UTC, sasakiyudai commented on src/app.gateway.ts
> +  handleConnection(@ConnectedSocket() client: Socket) {}
[e44b3b1](https://github.com/RIFT-tokyo/transcendence-api/pull/52/commits/e44b3b10ca47a0a3192f8fab63ae0e0a62f31358)で対応

2022-04-20 12:23 UTC, tkomatsu commented on src/users/users.gateway.ts
> +    await this.usersService.updateUser(userID, { status: status });
updateに失敗した時ってどうなりますか？

2022-04-20 12:44 UTC, sasakiyudai commented on src/users/users.gateway.ts
> +    await this.usersService.updateUser(userID, { status: status });
[7924ab8](https://github.com/RIFT-tokyo/transcendence-api/pull/52/commits/7924ab8e5eca9fd060d31f8945ff872c757d1b1a)でasync/awaitを削除

2022-04-22 08:46 UTC, tkomatsu commented
LGTM

2022-04-22 08:47 UTC, merged